export enum OrderStatus {
  CONFIRMED = "CONFIRMED",
  PROCESSING = "PROCESSING",
  DISPATCHED = "DISPATCHED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURNED = "RETURNED",
}
